name: NodeJS with Webpack

on:
    push:
        branches: ['production', 'staging']

env:
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
    ZONE_ID: ${{ secrets.ZONE_ID }}

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Install dependencies
              run: npm install --force

            - name: deploy aurigami
              run: npm run build-aurigami && npm run deploy-aurigami

            - name: deploy vesta
              run: npm run build-vesta && npm run deploy-vesta

            - name: deploy nervos
              run: npm run build-nervos && npm run deploy-nervos

            - name: deploy agave
              run: npm run build-agave && npm run deploy-agave

            - name: deploy meld
              run: npm run build-meld && npm run deploy-meld
